/*
 * Copyright by Akos Tajti (akos.tajti@gmail.com)
 *
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of Akos Tajti. ("Confidential Information"). You
 * shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement
 * you entered into with Akos Tajti.
 */
package net.docca.backend.search.indexers;

/**
 * thrown on any kind of indexing error.
 *
 * @author Akos Tajti <akos.tajti@gmail.com>
 *
 */
public class IndexingException extends Exception {
	/**
	 * generated by the compiler.
	 */
	private static final long serialVersionUID = 4757570518584032790L;

	/**
	 * the same onstructor as in the superclass.
	 * @param cause the exception causing this one.
	 */
	public IndexingException(final Throwable cause) {
		super(cause);
	}
}

