/*
 * Copyright by Akos Tajti (akos.tajti@gmail.com)
 *
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of Akos Tajti. ("Confidential Information"). You
 * shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement
 * you entered into with Akos Tajti.
 */
package net.docca.backend.search;

/**
 * thrown on any kind of search problem.
 *
 * @author Akos Tajti <akos.tajti@gmail.com>
 *
 */
public class SearchException extends Exception {

	/**
	 * the serial version id generated by the compiler.
	 */
	private static final long serialVersionUID = 8810149623951559390L;

	/**
	 * the default constructor.
	 */
	public SearchException() {
	}

	/**
	 * one-arg constructor. the same as in the super class.
	 * @param arg0 the cause
	 */
	public SearchException(final Throwable arg0) {
		super(arg0);
	}
}

